version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './:/app'
      - './php_fpm_site.conf:/etc/nginx/conf.d/php_fpm_site.conf'
    links:
      - fpm

  fpm:
    image: php:7.4.0RC4-fpm-alpine3.10
    volumes:
      - './:/app'