version: '3'

services:
  backend:
    image: node:12.16-web-server-alpine
    build:
      context: .docker
      dockerfile: node.Dockerfile
    ports:
      - 8081:80
    volumes:
      - './backend:/usr/app'

  frontend:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - './frontend:/usr/app'
      - './.docker/nginx.conf:/etc/nginx/nginx.conf'
